<?php
/**
 * @var \Kirill\Books\Block\Books\Form $block
 */
?>
<?php $book = $block->getAllData(); ?>
<div class="row">
    <div class="col-md-8">
        <form name="addData" method="post" id="addData" class="form"
              action="<?= $block->getFormAction(); ?>"
              data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
              data-mage-init='{"validation":{}}'>
            <fieldset class="fieldset">
                <legend class="legend"><span><?= $block->escapeHtmlAttr(__('Fill Detail')) ?></span></legend>
                <fieldset class="fieldset row">
                    <?php if ($book->getId()) : ?>
                        <input type="hidden" name="id" value="<?= $book->getId(); ?>">
                    <?php endif; ?>
                    <div class="fields col-md-6">
                        <div class="field name required">
                            <label class="label"
                                   for="title"><span><?= $block->escapeHtmlAttr(__('Name')) ?></span></label>
                            <div class="control">
                                <input name="name" id="name" title="Name" value="<?= $book->getName() ?>"
                                       class="input-text"
                                       type="text"
                                       data-validate="{required:true, 'validate-alphanum-with-spaces':true}">
                            </div>
                        </div>
                    </div>
                    <div class="fields col-md-6">
                        <div class="field name required">
                            <label class="label"
                                   for="title"><span><?= $block->escapeHtmlAttr(__('Author')) ?></span></label>
                            <div class="control">
                                <input name="author" id="author" title="author" value="<?= $book->getAuthor() ?>"
                                       class="input-text"
                                       type="text"
                                       data-validate="{required:true, 'validate-alphanum-with-spaces':true}">
                            </div>
                        </div>
                    </div>
                </fieldset>
            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" class="action submit primary" title="Save">
                        <span><?= $block->escapeHtmlAttr(__('Save')) ?></span></button>
                </div>
            </div>
        </form>
    </div>
</div>
